@startuml HSRTicketVendorSystemUseCase

left to right direction

usecase BuyTicket as "Buy Ticket
--
現場購買實體車票"

usecase PickUpTicket as "Pick Up Ticket
--
使用訂票代碼取票"

:User: --> BuyTicket
:User: --> PickUpTicket

@enduml